- set_fact:
    pma_version: 4.9.0.1

- name: install dependent package
  apt:
    name: "{{ item }}"
  loop:
    - nginx
    - php7.2-fpm
    - php7.2-mysqli
    - php7.2-mbstring

- name: download phpMyAdmin
  get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/{{ pma_version }}/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
    checksum: sha1:97c5ec2ecf53fda5e1b217ee64c3f5fde6bed032
    dest: /tmp/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
  register: pma

- block:
    - name: uninstall old phpMyAdmin
      file:
        path: /opt/phpMyAdmin
        state: absent
    - name: install phpMyAdmin
      unarchive:
        remote_src: yes
        src: /tmp/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
        dest: /opt
        owner: www-data
        group: www-data
    - name: move phpMyAdmin
      command: mv /opt/phpMyAdmin-{{ pma_version }}-all-languages /opt/phpMyAdmin
  when: pma.changed

- name: put config file
  template:
    src: config.inc.php
    dest: /opt/phpMyAdmin/config.inc.php

- name: put reverse proxy setting
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/phpmyadmin.conf

- name: restart services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
    state: restarted
  loop:
    - nginx
    - php7.2-fpm
