- set_fact:
    pma_version: 4.9.0.1

- name: install dependent package
  apt:
    name: "{{ item }}"
  loop:
    - nginx
    - hhvm

- name: download phpMyAdmin
  get_url:
    url: https://files.phpmyadmin.net/phpMyAdmin/{{ pma_version }}/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
    checksum: sha1:97c5ec2ecf53fda5e1b217ee64c3f5fde6bed032
    dest: /tmp/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
  register: pma

- block:
    - name: uninstall old phpMyAdmin
      file:
        path: /opt/phpMyAdmin-{{ pma_version }}-all-languages
        state: absent
    - name: install phpMyAdmin
      unarchive:
        remote_src: yes
        src: /tmp/phpMyAdmin-{{ pma_version }}-all-languages.tar.xz
        dest: /opt
  when: pma.changed

- name: put config file
  template:
    src: config.inc.php
    dest: /opt/phpMyAdmin-{{ pma_version }}-all-languages/config.inc.php

- name: put service definition
  template:
    src: phpmyadmin.service
    dest: /etc/systemd/system/phpmyadmin.service

- name: enable service
  systemd:
    name: phpmyadmin
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: put reverse proxy setting
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/phpmyadmin.conf

- name: restart nginx
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
