- name: install dstat (alternative of netdata!)
  apt:
    name: dstat

- name: download install script for netdata
  get_url:
    url: https://my-netdata.io/kickstart-static64.sh
    dest: /tmp/netdata.sh
    mode: 0755

- name: check netdata
  stat:
    path: /opt/netdata
  register: netdata

- name: install netdata
  shell: yes | /tmp/netdata.sh
  when: not netdata.stat.exists
