- name: clone repository
  git:
    repo: git@github.com:kaz/isucon9-app.git
    dest: ~/app
    accept_hostkey: yes

- name: check envfile
  stat:
    path: ~/env
  register: env

- name: touch envfile
  file:
    path: ~/env
    state: touch
  when: not env.stat.exists

- name: put deploy script
  copy:
    src: Makefile
    dest: ~/Makefile

- name: put service definition
  become_user: root
  template:
    src: isucon9-app.service
    dest: /etc/systemd/system/isucon9-app.service

- name: enable service
  become_user: root
  service:
    name: isucon9-app
    enabled: yes
    state: started
