- name: add deploy user
  user:
    name: "{{ bot_user }}"
    append: yes
    groups: wheel
    shell: /bin/bash

- become_user: "{{ bot_user }}"
  block:
    - name: make directory for deploy key
      file:
        path: ~/.ssh
        state: directory
        mode: 0700
    - name: add deploy key
      copy:
        src: deploy_key.pem
        dest: ~/.ssh/id_rsa
        mode: 0600

- import_tasks: deploy.yml
  become_user: "{{ bot_user }}"
