- name: add deploy user
  user:
    name: kiritan
    append: yes
    groups: wheel
    shell: /bin/bash

- name: add deploy key
  become_user: kiritan
  block:
    - file:
        path: /home/kiritan/.ssh
        state: directory
        mode: 0700
    - copy:
        src: deploy_key.pem
        dest: /home/kiritan/.ssh/id_rsa
        mode: 0600
