- name: clone repository
  become_user: "{{ bot_user }}"
  git:
    repo: git@github.com:kaz/isucon9-app.git
    dest: ~/app
    key_file: ~/.ssh/id_ed25519
    accept_hostkey: yes
    force: yes

- name: check envfile
  become_user: "{{ bot_user }}"
  stat:
    path: ~/env
  register: env

- name: touch envfile
  become_user: "{{ bot_user }}"
  file:
    path: ~/env
    state: touch
  when: not env.stat.exists

- name: put deploy script
  become_user: "{{ bot_user }}"
  copy:
    src: Makefile
    dest: ~/Makefile

- name: put service definition
  template:
    src: isucon9-app.service
    dest: /etc/systemd/system/isucon9-app.service

- name: enable service
  systemd:
    name: isucon9-app
    enabled: yes
    daemon_reload: yes
    state: restarted
