- name: add deploy user
  user:
    name: kiritan
    append: yes
    groups: wheel
    shell: /bin/bash

- become_user: kiritan
  block:
    - name: make directory for deploy key
      file:
        path: /home/kiritan/.ssh
        state: directory
        mode: 0700
    - name: add deploy key
      copy:
        src: deploy_key.pem
        dest: /home/kiritan/.ssh/id_rsa
        mode: 0600
