- name: clone repository
  become_user: "{{ bot_user }}"
  git:
    repo: git@github.com:kaz/isucon9-app.git
    dest: ~/app
    key_file: ~/.ssh/id_ed25519
    accept_hostkey: yes
    force: yes

- name: put envfile
  become_user: "{{ bot_user }}"
  template:
    src: env.sh
    dest: ~/env

- name: put deploy script
  become_user: "{{ bot_user }}"
  copy:
    src: "{{ item }}"
    dest: ~/{{ item }}
    mode: 0755
  loop:
    - deploy.sh
    - deploy_notify.sh

- name: put service definition
  template:
    src: app.service
    dest: /etc/systemd/system/app.service

- name: enable service
  systemd:
    name: app
    enabled: yes
    daemon_reload: yes
    state: restarted
