[slack]
url = "https://hooks.slack.com/services/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"
token = "{{ slack_token }}"
channel = "#stdout"
username = "{{ inventory_hostname_short }}"
icon_emoji = ":{{ inventory_hostname_short }}:"
interval = "1s"
