[slack]
url = "https://hooks.slack.com/services/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"
token = "{{ slack_token }}"
channel = "#stdout"
username = "{{ inventory_hostname_short }}"
icon_emoji = ":{{ inventory_hostname_short }}:"
interval = "1s"
