- name: install nginx
  apt:
    name: nginx

- name: check nginx conf
  stat:
    path: /etc/nginx/nginx.conf.orig
  register: conf

- name: backup nginx conf file
  copy:
    remote_src: yes
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf.orig
  when: not conf.stat.exists

- name: put nginx conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: create cache directory
  file:
    path: /var/cache/nginx/cache
    state: directory
    mode: 0777

- name: reload nginx
  service:
    name: nginx
    enabled: yes
    state: reloaded
