- hosts: db
  become: yes
  roles:
    - name: common.users
      tags:
        - common.users
    - name: common.hosts
      tags:
        - common.hosts
    - name: db.mysql
      tags:
        - db.mysql
    - name: db.users
      tags:
        - db.users
    - name: util.myprofiler
      tags:
        - util.myprofiler
