- hosts: lb
  become: yes
  roles:
    - name: common.users
      tags:
        - common.users
    - name: common.hosts
      tags:
        - common.hosts
    - name: lb.nginx
      tags:
        - lb.nginx
    - name: util.kataribe
      tags:
        - util.kataribe
