- hosts: app
  become: yes
  roles:
    - name: common.users
      tags:
        - common.users
    - name: app.golang
      tags:
        - app.golang
    - name: util.netdata
      tags:
        - util.netdata
    - name: util.notify_slack
      tags:
        - util.notify_slack
