- name: install dependent package
  apt:
    name: "{{ item }}"
  loop:
    - nginx

- name: install ssh tunneling service
  template:
    src: tunnel.service
    dest: /etc/systemd/system/tunnel-{{ item | regex_replace('\..+$') }}.service
  loop: "{{ groups['all'] }}"
  when: item != inventory_hostname

- name: enable ssh tunneling service
  systemd:
    name: tunnel-{{ item | regex_replace('\..+$') }}
    enabled: yes
    daemon_reload: yes
    state: restarted
  loop: "{{ groups['all'] }}"
  when: item != inventory_hostname

- name: put reverse proxy setting
  template:
    src: tunnel.conf
    dest: /etc/nginx/sites-enabled/tunnel-{{ item | regex_replace('\..+$') }}.conf
  loop: "{{ groups['all'] }}"
  when: item != inventory_hostname

- name: restart nginx
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
