- set_fact:
    target

- name: put portforward service for mysql
  template:
    src: pf-mysql.service
    dest: /etc/systemd/system/pf-mysql-{{ item | regex_replace('\..+$') }}.service
  loop: "{{ groups['all'] }}"
  when: "'mysql_forward' in hostvars[item]"

- name: enable portforward service for mysql
  systemd:
    name: pf-mysql-{{ item | regex_replace('\..+$') }}
    enabled: yes
    daemon_reload: yes
    state: restarted
  loop: "{{ groups['all'] }}"
  when: "'mysql_forward' in hostvars[item]"

- name: put portforward service for netdata
  template:
    src: pf-netdata.service
    dest: /etc/systemd/system/pf-netdata-{{ item | regex_replace('\..+$') }}.service
  loop: "{{ groups['all'] }}"
  when: "'netdata_forward' in hostvars[item]"

- name: enable portforward service for netdata
  systemd:
    name: pf-netdata-{{ item | regex_replace('\..+$') }}
    enabled: yes
    daemon_reload: yes
    state: restarted
  loop: "{{ groups['all'] }}"
  when: "'netdata_forward' in hostvars[item]"
